In [1]:
import pandas as pd

In [3]:
import requests

In [11]:
import requests

url = "https://facebook-scraper3.p.rapidapi.com/ads/page/search"

params = {
    "page_id": "118526624562575",
    "country": "US",
    "active_status": "ALL",
    "sort_by_new": "false"
}

headers = {
    "x-rapidapi-key": "9952e905c0msh29bd2e7ab76bb84p1219ebjsnc54cc4e587b7",
    "x-rapidapi-host": "facebook-scraper3.p.rapidapi.com"
}

response = requests.get(url, params=params, headers=headers)

print(response.status_code)
print(response.text)

200
{"ads":[{"ad_archive_id":"1606151587808590","collation_count":null,"collation_id":null,"is_active":true,"page_id":"118526624562575","page_is_deleted":false,"snapshot":{"branded_content":{"page_id":"118526624562575","page_is_deleted":false,"page_profile_uri":"https://facebook.com/TemuPoland","page_name":"Temu Poland"},"page_id":"243389615515469","page_is_deleted":false,"page_profile_uri":"https://facebook.com/61555728907339","root_reshared_post":null,"byline":null,"disclaimer_label":null,"page_name":"Brighter right ","page_profile_picture_url":"https://scontent.fdxb1-1.fna.fbcdn.net/v/t39.35426-6/774281601_899030309943058_9162811229350920438_n.jpg?stp=dst-jpg_s60x60_tt6&_nc_cat=104&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=5fq18bFSw-8Q7kNvwET8zz8&_nc_oc=AdrPQ0FXZ3fcpdDYpCcBzhLaOJEA_O-IFjzxemhJbhEsJz-WIqCzPjWW903o3hpAjws&_nc_zt=14&_nc_ht=scontent.fdxb1-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQGawEtfDQJSUuOqBqoEZUgJrU3lWobT1J9zIomlwgSMdw&oe=6A83D788","event":null,"caption":"temu.com","cta_text":"Shop now","cards":[],"body":{"text":"Discover a wide range of amazing deals & enjoy free shipping on Temu"},"cta_type":"SHOP_NOW","display_format":"IMAGE","link_description":null,"link_url":"https://www.temu.com/ul/kuiper/un1.html?subj=feed-un&_bg_fs=1&_p_mat1_type=1&_p_jump_id=725&_x_vst_scene=adg&locale_override=211~en~USD&adg_ctx=a-4d836a89&goods_id=601099574796236&_p_rfs=1&_x_ads_channel=kol_metabca&_x_ads_sub_channel=influencer&_x_bg_adid=udp2012481387&_x_ads_set={{campaign.id}}&_x_ads_id={{adset.id}}&_x_ads_creative_id={{ad.id}}&_x_ns_source={{site_source_name}}&_x_ns_placement={{placement}}","images":[{"image_crops":[],"original_image_url":"https://scontent.fdxb2-1.fna.fbcdn.net/v/t39.35426-6/773240316_1737853847253391_1962315907103893159_n.jpg?_nc_cat=100&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=siNaV9Ym-S4Q7kNvwGovDuG&_nc_oc=AdpaptEa1-YTnQxy1R0Gg8vNHOs8r2NOKPMgGT_fmTvMJfgRs9e3tKTY5nEB8nzG6wk&_nc_zt=14&_nc_ht=scontent.fdxb2-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQGqZ-ObA0lJBJy8tcrs7i1J5GRXGvDHRgnuMJyVBSa1zw&oe=6A83DFFB","resized_image_url":"https://scontent.fdxb5-1.fna.fbcdn.net/v/t39.35426-6/773662483_1892473231731431_8337599946785486707_n.jpg?stp=dst-jpg_s600x600_tt6&_nc_cat=109&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=07y4JrtwbSMQ7kNvwEbIsHz&_nc_oc=Adq9AR0YVIYZm1Gj6KK6DvYc7qUacCXT6sAJQ0BEr6531QgmiTPgor6J2B1bk8uyKos&_nc_zt=14&_nc_ht=scontent.fdxb5-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQHZtf-nLEPFpPeQOJEg_3Tc9Y299g_x-0gbOVR3YJzNCQ&oe=6A83D601","watermarked_resized_image_url":""}],"page_categories":["Public figure"],"page_like_count":13971,"title":"Temu | Explore the Latest Clothing, Beauty, Home, Jewelry & More","videos":[],"is_reshared":false,"extra_links":[],"extra_texts":[],"extra_images":[],"extra_videos":[],"country_iso_code":null,"brazil_tax_id":null,"additional_info":null,"ec_certificates":[]},"has_user_reported":false,"report_count":null,"menu_items":[],"state_media_run_label":null,"page_name":"Temu Poland","impressions_with_index":{"impressions_text":null,"impressions_index":-1},"gated_type":"ELIGIBLE","categories":["UNKNOWN"],"is_aaa_eligible":false,"contains_digital_created_media":false,"reach_estimate":null,"currency":"","spend":null,"end_date":1786604400,"publisher_platform":["FACEBOOK","INSTAGRAM","AUDIENCE_NETWORK","MESSENGER","THREADS"],"start_date":1786518000,"contains_sensitive_content":false,"total_active_time":19610,"regional_regulation_data":{"finserv":{"is_deemed_finserv":false,"is_limited_delivery":false},"tw_anti_scam":{"is_limited_delivery":false}},"hide_data_status":"NONE","fev_info":null,"ad_id":null,"targeted_or_reached_countries":[]},{"ad_archive_id":"1486156853269724","collation_count":null,"collation_id":null,"is_active":true,"page_id":"118526624562575","page_is_deleted":false,"snapshot":{"branded_content":{"page_id":"118526624562575","page_is_deleted":false,"page_profile_uri":"https://facebook.com/TemuPoland","page_name":"Temu Poland"},"page_id":"243389615515469","page_is_deleted":false,"page_profile_uri":"https://facebook.com/61555728907339","root_reshared_post":null,"byline":null,"disclaimer_label":null,"page_name":"Brighter right ","page_profile_picture_url":"https://scontent.fdxb1-1.fna.fbcdn.net/v/t39.35426-6/768963042_1060226176550584_4825398684669168459_n.jpg?stp=dst-jpg_s60x60_tt6&_nc_cat=108&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=umcclq5VYREQ7kNvwGNK3Xx&_nc_oc=AdrS-4FjGzObrGI-PtOwXjLy94319h-H4SMWBPlyhYpZGWK-5QNXME_5PIxYR5V_k-k&_nc_zt=14&_nc_ht=scontent.fdxb1-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQHN80N6H4BHVXsvuVCw6zpLC-MZfpAm_9SJxhOjsLjKVA&oe=6A83E7E3","event":null,"caption":"temu.com","cta_text":"Shop now","cards":[],"body":{"text":"Discover a wide range of amazing deals & enjoy free shipping on Temu"},"cta_type":"SHOP_NOW","display_format":"IMAGE","link_description":null,"link_url":"https://www.temu.com/ul/kuiper/un1.html?subj=feed-un&_bg_fs=1&_p_mat1_type=1&_p_jump_id=725&_x_vst_scene=adg&locale_override=211~en~USD&adg_ctx=a-4d836a89&goods_id=601099574796236&_p_rfs=1&_x_ads_channel=kol_metabca&_x_ads_sub_channel=influencer&_x_bg_adid=udp2012469831&_x_ads_set={{campaign.id}}&_x_ads_id={{adset.id}}&_x_ads_creative_id={{ad.id}}&_x_ns_source={{site_source_name}}&_x_ns_placement={{placement}}","images":[{"image_crops":[],"original_image_url":"https://scontent.fdxb1-1.fna.fbcdn.net/v/t39.35426-6/770919252_3960120697617950_7805306785071873821_n.jpg?_nc_cat=110&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=d-h0wD313JwQ7kNvwG8EKym&_nc_oc=Adoywl4nvRn7HCQQ5Okslm-MXH5RZMgJy22ngl3tJ7YwlibUxn3gMz3QP32nigTYeHI&_nc_zt=14&_nc_ht=scontent.fdxb1-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQHfnaA5R9Qe1Q5Ns9SsDI3tNxXVCtHWgVTOp6c4dAm7kw&oe=6A83D3FF","resized_image_url":"https://scontent.fdxb1-1.fna.fbcdn.net/v/t39.35426-6/769345768_1049449198042832_5442544170648607355_n.jpg?stp=dst-jpg_s600x600_tt6&_nc_cat=107&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=dvaXIDvDhRkQ7kNvwGiy61s&_nc_oc=Ado2EToHBdwoFfR-P7-lNlZV_W6AeXM31EF-6Xh4xB624-AMSVPJ1d2aqte3ZQJ5JdE&_nc_zt=14&_nc_ht=scontent.fdxb1-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQEsMad9bupWYGuPbDcfKwLgDYinm_JghYxyv70QV79MbA&oe=6A83E28F","watermarked_resized_image_url":""}],"page_categories":["Public figure"],"page_like_count":13971,"title":"Temu | Explore the Latest Clothing, Beauty, Home, Jewelry & More","videos":[],"is_reshared":false,"extra_links":[],"extra_texts":[],"extra_images":[],"extra_videos":[],"country_iso_code":null,"brazil_tax_id":null,"additional_info":null,"ec_certificates":[]},"has_user_reported":false,"report_count":null,"menu_items":[],"state_media_run_label":null,"page_name":"Temu Poland","impressions_with_index":{"impressions_text":null,"impressions_index":-1},"gated_type":"ELIGIBLE","categories":["UNKNOWN"],"is_aaa_eligible":false,"contains_digital_created_media":false,"reach_estimate":null,"currency":"","spend":null,"end_date":1786604400,"publisher_platform":["FACEBOOK","INSTAGRAM","AUDIENCE_NETWORK","MESSENGER","WHATSAPP","THREADS"],"start_date":1786518000,"contains_sensitive_content":false,"total_active_time":83784,"regional_regulation_data":{"finserv":{"is_deemed_finserv":false,"is_limited_delivery":false},"tw_anti_scam":{"is_limited_delivery":false}},"hide_data_status":"NONE","fev_info":null,"ad_id":null,"targeted_or_reached_countries":[]}],"cursor":null}

In [12]:
response

In [21]:
df = response.json()

In [22]:
df

{'ads': [{'ad_archive_id': '1606151587808590',
   'collation_count': None,
   'collation_id': None,
   'is_active': True,
   'page_id': '118526624562575',
   'page_is_deleted': False,
   'snapshot': {'branded_content': {'page_id': '118526624562575',
     'page_is_deleted': False,
     'page_profile_uri': 'https://facebook.com/TemuPoland',
     'page_name': 'Temu Poland'},
    'page_id': '243389615515469',
    'page_is_deleted': False,
    'page_profile_uri': 'https://facebook.com/61555728907339',
    'root_reshared_post': None,
    'byline': None,
    'disclaimer_label': None,
    'page_name': 'Brighter right ',
    'page_profile_picture_url': 'https://scontent.fdxb1-1.fna.fbcdn.net/v/t39.35426-6/774281601_899030309943058_9162811229350920438_n.jpg?stp=dst-jpg_s60x60_tt6&_nc_cat=104&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=5fq18bFSw-8Q7kNvwET8zz8&_nc_oc=AdrPQ0FXZ3fcpdDYpCcBzhLaOJEA_O-IFjzxemhJbhEsJz-WIqCzPjWW903o3hpAjws&_nc_zt=14&_nc_ht=scontent.fdxb1-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQGawEtfDQJSUuOqBqoEZUgJrU3lWobT1J9zIomlwgSMdw&oe=6A83D788',
    'event': None,
    'caption': 'temu.com',
    'cta_text': 'Shop now',
    'cards': [],
    'body': {'text': 'Discover a wide range of amazing deals & enjoy free shipping on Temu'},
    'cta_type': 'SHOP_NOW',
    'display_format': 'IMAGE',
    'link_description': None,
    'link_url': 'https://www.temu.com/ul/kuiper/un1.html?subj=feed-un&_bg_fs=1&_p_mat1_type=1&_p_jump_id=725&_x_vst_scene=adg&locale_override=211~en~USD&adg_ctx=a-4d836a89&goods_id=601099574796236&_p_rfs=1&_x_ads_channel=kol_metabca&_x_ads_sub_channel=influencer&_x_bg_adid=udp2012481387&_x_ads_set={{campaign.id}}&_x_ads_id={{adset.id}}&_x_ads_creative_id={{ad.id}}&_x_ns_source={{site_source_name}}&_x_ns_placement={{placement}}',
    'images': [{'image_crops': [],
      'original_image_url': 'https://scontent.fdxb2-1.fna.fbcdn.net/v/t39.35426-6/773240316_1737853847253391_1962315907103893159_n.jpg?_nc_cat=100&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=siNaV9Ym-S4Q7kNvwGovDuG&_nc_oc=AdpaptEa1-YTnQxy1R0Gg8vNHOs8r2NOKPMgGT_fmTvMJfgRs9e3tKTY5nEB8nzG6wk&_nc_zt=14&_nc_ht=scontent.fdxb2-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQGqZ-ObA0lJBJy8tcrs7i1J5GRXGvDHRgnuMJyVBSa1zw&oe=6A83DFFB',
      'resized_image_url': 'https://scontent.fdxb5-1.fna.fbcdn.net/v/t39.35426-6/773662483_1892473231731431_8337599946785486707_n.jpg?stp=dst-jpg_s600x600_tt6&_nc_cat=109&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=07y4JrtwbSMQ7kNvwEbIsHz&_nc_oc=Adq9AR0YVIYZm1Gj6KK6DvYc7qUacCXT6sAJQ0BEr6531QgmiTPgor6J2B1bk8uyKos&_nc_zt=14&_nc_ht=scontent.fdxb5-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQHZtf-nLEPFpPeQOJEg_3Tc9Y299g_x-0gbOVR3YJzNCQ&oe=6A83D601',
      'watermarked_resized_image_url': ''}],
    'page_categories': ['Public figure'],
    'page_like_count': 13971,
    'title': 'Temu | Explore the Latest Clothing, Beauty, Home, Jewelry & More',
    'videos': [],
    'is_reshared': False,
    'extra_links': [],
    'extra_texts': [],
    'extra_images': [],
    'extra_videos': [],
    'country_iso_code': None,
    'brazil_tax_id': None,
    'additional_info': None,
    'ec_certificates': []},
   'has_user_reported': False,
   'report_count': None,
   'menu_items': [],
   'state_media_run_label': None,
   'page_name': 'Temu Poland',
   'impressions_with_index': {'impressions_text': None,
    'impressions_index': -1},
   'gated_type': 'ELIGIBLE',
   'categories': ['UNKNOWN'],
   'is_aaa_eligible': False,
   'contains_digital_created_media': False,
   'reach_estimate': None,
   'currency': '',
   'spend': None,
   'end_date': 1786604400,
   'publisher_platform': ['FACEBOOK',
    'INSTAGRAM',
    'AUDIENCE_NETWORK',
    'MESSENGER',
    'THREADS'],
   'start_date': 1786518000,
   'contains_sensitive_content': False,
   'total_active_time': 19610,
   'regional_regulation_data': {'finserv': {'is_deemed_finserv': False,
     'is_limited_delivery': False},
    'tw_anti_scam': {'is_limited_delivery': False}},
   'hide_data_status': 'NONE',
   'fev_info': None,
   'ad_id': None,
   'targeted_or_reached_countries': []},
  {'ad_archive_id': '1486156853269724',
   'collation_count': None,
   'collation_id': None,
   'is_active': True,
   'page_id': '118526624562575',
   'page_is_deleted': False,
   'snapshot': {'branded_content': {'page_id': '118526624562575',
     'page_is_deleted': False,
     'page_profile_uri': 'https://facebook.com/TemuPoland',
     'page_name': 'Temu Poland'},
    'page_id': '243389615515469',
    'page_is_deleted': False,
    'page_profile_uri': 'https://facebook.com/61555728907339',
    'root_reshared_post': None,
    'byline': None,
    'disclaimer_label': None,
    'page_name': 'Brighter right ',
    'page_profile_picture_url': 'https://scontent.fdxb1-1.fna.fbcdn.net/v/t39.35426-6/768963042_1060226176550584_4825398684669168459_n.jpg?stp=dst-jpg_s60x60_tt6&_nc_cat=108&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=umcclq5VYREQ7kNvwGNK3Xx&_nc_oc=AdrS-4FjGzObrGI-PtOwXjLy94319h-H4SMWBPlyhYpZGWK-5QNXME_5PIxYR5V_k-k&_nc_zt=14&_nc_ht=scontent.fdxb1-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQHN80N6H4BHVXsvuVCw6zpLC-MZfpAm_9SJxhOjsLjKVA&oe=6A83E7E3',
    'event': None,
    'caption': 'temu.com',
    'cta_text': 'Shop now',
    'cards': [],
    'body': {'text': 'Discover a wide range of amazing deals & enjoy free shipping on Temu'},
    'cta_type': 'SHOP_NOW',
    'display_format': 'IMAGE',
    'link_description': None,
    'link_url': 'https://www.temu.com/ul/kuiper/un1.html?subj=feed-un&_bg_fs=1&_p_mat1_type=1&_p_jump_id=725&_x_vst_scene=adg&locale_override=211~en~USD&adg_ctx=a-4d836a89&goods_id=601099574796236&_p_rfs=1&_x_ads_channel=kol_metabca&_x_ads_sub_channel=influencer&_x_bg_adid=udp2012469831&_x_ads_set={{campaign.id}}&_x_ads_id={{adset.id}}&_x_ads_creative_id={{ad.id}}&_x_ns_source={{site_source_name}}&_x_ns_placement={{placement}}',
    'images': [{'image_crops': [],
      'original_image_url': 'https://scontent.fdxb1-1.fna.fbcdn.net/v/t39.35426-6/770919252_3960120697617950_7805306785071873821_n.jpg?_nc_cat=110&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=d-h0wD313JwQ7kNvwG8EKym&_nc_oc=Adoywl4nvRn7HCQQ5Okslm-MXH5RZMgJy22ngl3tJ7YwlibUxn3gMz3QP32nigTYeHI&_nc_zt=14&_nc_ht=scontent.fdxb1-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQHfnaA5R9Qe1Q5Ns9SsDI3tNxXVCtHWgVTOp6c4dAm7kw&oe=6A83D3FF',
      'resized_image_url': 'https://scontent.fdxb1-1.fna.fbcdn.net/v/t39.35426-6/769345768_1049449198042832_5442544170648607355_n.jpg?stp=dst-jpg_s600x600_tt6&_nc_cat=107&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=c53f8f&_nc_ohc=dvaXIDvDhRkQ7kNvwGiy61s&_nc_oc=Ado2EToHBdwoFfR-P7-lNlZV_W6AeXM31EF-6Xh4xB624-AMSVPJ1d2aqte3ZQJ5JdE&_nc_zt=14&_nc_ht=scontent.fdxb1-1.fna&_nc_gid=IDrntYmC141EL8CMSyUq0w&_nc_ss=7f180&oh=00_AQEsMad9bupWYGuPbDcfKwLgDYinm_JghYxyv70QV79MbA&oe=6A83E28F',
      'watermarked_resized_image_url': ''}],
    'page_categories': ['Public figure'],
    'page_like_count': 13971,
    'title': 'Temu | Explore the Latest Clothing, Beauty, Home, Jewelry & More',
    'videos': [],
    'is_reshared': False,
    'extra_links': [],
    'extra_texts': [],
    'extra_images': [],
    'extra_videos': [],
    'country_iso_code': None,
    'brazil_tax_id': None,
    'additional_info': None,
    'ec_certificates': []},
   'has_user_reported': False,
   'report_count': None,
   'menu_items': [],
   'state_media_run_label': None,
   'page_name': 'Temu Poland',
   'impressions_with_index': {'impressions_text': None,
    'impressions_index': -1},
   'gated_type': 'ELIGIBLE',
   'categories': ['UNKNOWN'],
   'is_aaa_eligible': False,
   'contains_digital_created_media': False,
   'reach_estimate': None,
   'currency': '',
   'spend': None,
   'end_date': 1786604400,
   'publisher_platform': ['FACEBOOK',
    'INSTAGRAM',
    'AUDIENCE_NETWORK',
    'MESSENGER',
    'WHATSAPP',
    'THREADS'],
   'start_date': 1786518000,
   'contains_sensitive_content': False,
   'total_active_time': 83784,
   'regional_regulation_data': {'finserv': {'is_deemed_finserv': False,
     'is_limited_delivery': False},
    'tw_anti_scam': {'is_limited_delivery': False}},
   'hide_data_status': 'NONE',
   'fev_info': None,
   'ad_id': None,
   'targeted_or_reached_countries': []}],
 'cursor': None}

In [23]:
type(df)

dict

In [29]:
temp_df = pd.DataFrame(df)

In [30]:
temp_df

                                                 ads cursor
0  {'ad_archive_id': '1606151587808590', 'collati...   None
1  {'ad_archive_id': '1486156853269724', 'collati...   None

In [31]:
temp_df.head()

                                                 ads cursor
0  {'ad_archive_id': '1606151587808590', 'collati...   None
1  {'ad_archive_id': '1486156853269724', 'collati...   None

In [32]:
temp_df.shape

(2, 2)

In [33]:
temp_df = pd.DataFrame(df['ads'])

In [34]:
temp_df

,ad_archive_id,collation_count,collation_id,is_active,page_id,page_is_deleted,snapshot,has_user_reported,report_count,menu_items,...,end_date,publisher_platform,start_date,contains_sensitive_content,total_active_time,regional_regulation_data,hide_data_status,fev_info,ad_id,targeted_or_reached_countries
0,1606151587808590,None,None,True,118526624562575,False,{'branded_content': {'page_id': '1185266245625...,False,None,[],...,1786604400,"[FACEBOOK, INSTAGRAM, AUDIENCE_NETWORK, MESSEN...",1786518000,False,19610,"{'finserv': {'is_deemed_finserv': False, 'is_l...",NONE,None,None,[]
1,1486156853269724,None,None,True,118526624562575,False,{'branded_content': {'page_id': '1185266245625...,False,None,[],...,1786604400,"[FACEBOOK, INSTAGRAM, AUDIENCE_NETWORK, MESSEN...",1786518000,False,83784,"{'finserv': {'is_deemed_finserv': False, 'is_l...",NONE,None,None,[]

In [35]:
temp_df = pd.json_normalize(df['ads'])

In [36]:
temp_df

,ad_archive_id,collation_count,collation_id,is_active,page_id,page_is_deleted,has_user_reported,report_count,menu_items,state_media_run_label,...,snapshot.extra_videos,snapshot.country_iso_code,snapshot.brazil_tax_id,snapshot.additional_info,snapshot.ec_certificates,impressions_with_index.impressions_text,impressions_with_index.impressions_index,regional_regulation_data.finserv.is_deemed_finserv,regional_regulation_data.finserv.is_limited_delivery,regional_regulation_data.tw_anti_scam.is_limited_delivery
0,1606151587808590,None,None,True,118526624562575,False,False,None,[],None,...,[],None,None,None,[],None,-1,False,False,False
1,1486156853269724,None,None,True,118526624562575,False,False,None,[],None,...,[],None,None,None,[],None,-1,False,False,False

In [37]:
temp_df.to_csv("facebook_ads_dataset.csv", index=False)

In [38]:
temp_df.head()

,ad_archive_id,collation_count,collation_id,is_active,page_id,page_is_deleted,has_user_reported,report_count,menu_items,state_media_run_label,...,snapshot.extra_videos,snapshot.country_iso_code,snapshot.brazil_tax_id,snapshot.additional_info,snapshot.ec_certificates,impressions_with_index.impressions_text,impressions_with_index.impressions_index,regional_regulation_data.finserv.is_deemed_finserv,regional_regulation_data.finserv.is_limited_delivery,regional_regulation_data.tw_anti_scam.is_limited_delivery
0,1606151587808590,None,None,True,118526624562575,False,False,None,[],None,...,[],None,None,None,[],None,-1,False,False,False
1,1486156853269724,None,None,True,118526624562575,False,False,None,[],None,...,[],None,None,None,[],None,-1,False,False,False