In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
df['Gender'].replace({'Male' : 0 , 'Female' : 1} , inplace= True)

In [7]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       0   19            19000          0
1    15810944       0   35            20000          0
2    15668575       1   26            43000          0
3    15603246       1   27            57000          0
4    15804002       0   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       1   46            41000          1
396  15706071       0   51            23000          1
397  15654296       1   50            20000          1
398  15755018       0   36            33000          0
399  15594041       1   49            36000          1

[400 rows x 5 columns]

In [8]:
X = df.iloc[: , 1:4].values
y = df.iloc[: , -1].values

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
X = scaler.fit_transform(X)

In [16]:
X

array([[-1.02020406, -1.78179743, -1.49004624],
       [-1.02020406, -0.25358736, -1.46068138],
       [ 0.98019606, -1.11320552, -0.78528968],
       ...,
       [ 0.98019606,  1.17910958, -1.46068138],
       [-1.02020406, -0.15807423, -1.07893824],
       [ 0.98019606,  1.08359645, -0.99084367]], shape=(400, 3))

In [19]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train  , y_test = train_test_split(X,y,test_size=0.2 , random_state=1)

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
tr = DecisionTreeClassifier()

In [22]:
tr.fit(X_train , y_train)

DecisionTreeClassifier()

In [23]:
y_pred = tr.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.7875

In [25]:
## hyperparameter tunning using gridsearchcv

In [29]:
param_dist = {
    "criterion" : ["gini" , "entropy"],
    "max_depth" : [1,2,3,4,5,6,7,None]
    
}

In [32]:
from sklearn.model_selection  import GridSearchCV

In [33]:
grid = GridSearchCV(tr , param_grid=param_dist , cv =10 , n_jobs =1)

In [34]:
grid.fit(X_train , y_train)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_jobs=1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, None]})

In [35]:
grid.best_estimator_

DecisionTreeClassifier(max_depth=2)

In [36]:
grid.best_score_

np.float64(0.91875)

In [37]:
grid.best_params_

{'criterion': 'gini', 'max_depth': 2}