In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [3]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df1 = pd.DataFrame(data_list)
df1

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [4]:
# remove index and add columns means set manualy
columns = ["name" , "age" , "city" , "salary"]
df1 = pd.DataFrame(data_list , columns=columns)
df1

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
df["Salary"]

0    65000
1    70000
2    62000
3    85000
Name: Salary, dtype: int64

In [6]:
# if want to accsess two or more columns 
#list [['column', 'column']]

In [7]:
df[["Name","Salary"]]

    Name  Salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [8]:
df["Designation"] = ["doctor" ,"eng" , "doctor" ,"eng"]
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         eng

In [9]:

df.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000      doctor
1  Anna   34     Paris   70000         eng

In [10]:
df.iloc[3]

Name            Linda
Age                42
City           London
Salary          85000
Designation       eng
Name: 3, dtype: object

In [12]:
df.loc[[0,1]][["City" , "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [14]:
df.loc[[2,3]][["Name" , "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [18]:
df[df["Age" ] > 30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000         eng
3  Linda   42  London   85000         eng

In [19]:
df[(df["Age"] > 30) & (df["City"] == "Paris")]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000         eng